baseURL: "https://yuanmoe.com/"
LanguageCode: zh-cn
theme: PaperMod
title: YuanMoe
paginate: 5

markup:
  goldmark:
    renderer:
      unsafe: true

buildDrafts: false
buildExpired: false
buildFuture: false
enableEmoji: true
enableRobotsTXT: true

permalinks:
  posts: posts/:filename

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  DateFormat: "January 2, 2006"
  author: YuanMoe
  description: "多远才算是离开的距离"
  images: ["favicon.svg"]
  title: YuanMoe
  comments: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  defaultTheme: auto

  assets:
    disableHLJS: true
    favicon: "favicon.ico"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "apple-touch-icon-precomposed.png"

  profileMode:
    enabled: true
    title: "YuanMoe"
    subtitle: "多远才算是离开的距离"
    imageUrl: "favicon.svg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: avatar

  socialIcons:
    - name: github
      url: "https://github.com/yuanmoe"
    - name: kofi
      url: "https://yuanmoe.com/coffee/"
    - name: "rss"
      url: "https://yuanmoe.com/index.xml"

menu:
  main:
    - identifier: index
      name: 首页
      url: /
      weight: 10
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 20
    - identifier: search
      name: 搜索
      url: /search/
      weight: 30
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 40
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 50
    - identifier: comments
      name: 留言
      url: /comments/
      weight: 60
    - identifier: links
      name: 友链
      url: /links/
      weight: 70
    - identifier: about
      name: 关于
      url: /about/
      weight: 80
    

privacy:
  youtube:
    privacyEnhanced: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
